### ISSUE TITLE
Validator should only validate modified beans

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#22]
In our use case, IBeanValidator implementations registered for a BeanDtoDescriptorBuilder should only be called for modified beans, not for all loaded beans. This would decrease the performance!

jo-cap 0.26.0 / jo-widgets 0.29.0 implemented validation only for modified beans.
After we updated to jo-cap 0.42.0 / jo-widgets 0.47.0 all loaded beans are validated which caused a client hang when loading a table with many beans.

Das Verhalten führt auch dazu, dass bei ungültigen Beans (z.B. erzeugt durch Import) überhaupt nichts mehr gespeichert werden kann.

**Comment by herrgrossmann** [comment]
Problem mit Comit 1d2bde534ffa40e9e2cd61183c5f747595f6cd25 behoben. Funktion ist ab jo-client-platform 0.50.0 verfügbar.
Im kitchensink2 example zeigt der folgende Comit 00351e56cd3a8f6f8e134566298f1ea41ed2d305 wie die Funktion global aktiviert werden kann.

**Comment by herrgrossmann** [comment]
Leave a comment

**Comment by abentele** [comment]
Getestet. Sieht gut aus!
