### ISSUE TITLE
Service decorator doesn't work for links

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#25]
Use case: service decorator für Update- und Creator-Service, um den Benutzer beim Anlegen eines Duplikats zu warnen: der User bekommt einen Hinweis der Art: "Der Name ist nicht eindeutig. Möchten Sie wirklich ein Duplikat anlegen?", welchen er mit "Ok" oder "Cancel" bestätigen kann.

Die Service Decorator wurden entsprechend registriert, funktionieren jedoch nicht im Zusammenhang mit Links: legt man einen neuen Link inkl. neuem Bean an, wird der Service Decorator nicht verwendet, sondern der Default Update-Service bzw. Default Creator-Service.

Ich habe das nochmal genauer analysiert. Vielleicht liegt das Problem in 
```Java
org.jowidgets.cap.service.impl.BeanEntityServiceBuilderImpl.BeanEntityLinkBluePrintImpl.createLinkServicesBuilder(Map<Object, BeanEntityPreBuild>)
```

Der Code 

```Java
builder.setLinkableCreatorService(createCreatorService(linkableBeanType, linkableBeanTypeId, linkableProperties));
builder.setLinkableDeleterService(createDeleterService(linkableBeanType, linkableBeanTypeId));
```

müsste vermutlich so aussehen:

```Java
builder.setLinkableCreatorService(linkablePrebuild. getCreatorService());
builder.setLinkableDeleterService(linkablePrebuild. getDeleterService());
```

**Comment by herrgrossmann** [comment]
Das Problem konnte ich nachstellen. Der vorgeschlagene Patch funktioniert bei mir aber nicht.

builder.setLinkableCreatorService(linkablePrebuild. getCreatorService());
builder.setLinkableDeleterService(linkablePrebuild. getDeleterService());

Getestet in Kitchensink2, Komponente Users, Hinzufügen einer Person zu einer Rolle. Personen Creator Service wurde dekoriert.

**Comment by abentele** [comment]
Verifiziert: Test ok.
