### ISSUE TITLE
Add link funktioniert nicht mehr bei Darstellung von Readonly-Properties im Bearbeitungsdialog

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#28]
- Use case: Hinzufügen eines neuen Link Datensatzes mit dem Kommando "Add ..."
=> hier kommt die Fehlermeldung: "java.lang.IllegalStateException: No attribute found for the property 'creator'."

- Sourcecode (Auszug), wobei das Property "creator" readonly ist

```java
public class FormPlugin extends AbstractBeanFormPlugin {

	@Override
	public void modifySetup(final IBeanFormBluePrint<?> bluePrint) {
		bluePrint.setCreateModeLayouter(FormLayouterFactory.create(false));
		bluePrint.setEditModeLayouter(FormLayouterFactory.create(true));
	}

}

public final class FormLayouterFactory {

	private FormLayouterFactory () {}

	public static IBeanFormLayouter create(final boolean editMode) {
		final IBeanFormLayoutBuilder builder = BeanFormToolkit.layoutBuilder();
		builder.setColumnCount(2);
		builder.addGroup(createGroup(editMode));
		return BeanFormToolkit.layouter(builder.build());
	}

	private static IBeanFormGroup createGroup(final boolean editMode) {
		final IBeanFormGroupBuilder builder = BeanFormToolkit.groupBuilder();
		builder.addProperty(...);
                ...

		if (editMode) {
			builder.addProperty("creator");
			builder.addProperty("creationDate");
                        ...
		}

		return builder.build();
	}
}

```

- würde man die folgenden Zeilen auskommentieren, würde der Fehler nicht mehr auftreten (das ist aber keine Lösung):
```java
			builder.addProperty("creator");
			builder.addProperty("creationDate");
```

- der Fehler kommt durch Update auf neueres jocap bzw. jowidgets release:
jo-client-platform 0.31.0 / jo-widgets 0.34.0 => Fehler tritt nicht auf
jo-client-platform 0.32.0 / jo-widgets 0.35.0 => Fehler tritt auf

- genauer gesagt bewirkt der commit 7dba0abfc2f53bceec6fd69852ed278ae72d725e in jo-client-platform den Fehler (der Stand unmittelbar davor, d.h. commit 199d27ea3822aef9a026b103745ccfccb531a057, hat den Fehler noch nicht!)

- Vermutung: in LinkCreatorActionBuilderImpl#getFilteredAttributes() wurde die Bedingung attribute.isEditable() hinzugefügt; genau diese Bedingung filtert das Attribut "creator" heraus.

Eine Frage die sich mir hier noch stellt, ist: wenn man per "Add..." einen neuen Link-Datensatz anlegen möchte (wie hier), dann müsste doch der mit setCreateModeLayouter konfigurierte Layouter verwendet werden, und da ist ja editMode = false bzw. das Property "creator" wird gar nicht hinzugefügt. Warum also tritt der Fehler hier überhaupt so zutage?

Meine interne Ticket-Nr.: #7944

**Comment by abentele** [comment]
hier noch weitere Erläuterungen:

-	Entities: A, B
-	A hat Property: ```Set<B> setOfB``` (JPA: @OneToMany, also 1:n Beziehung)
-	B hat property ```A a``` (@ManyToOne, Foreign-Key auf A)
-	B hat Properties ```creator``` und ```creationDate``` (beide implizit readonly, weil entsprechende setter-Methoden nicht im Interface enthalten sind)

Auszug aus Sourcecode:

```Java
	private void addBLinkDescriptor(final IBeanEntityBluePrint entityBp) {
		final IBeanEntityLinkBluePrint bp = entityBp.addLink();
		bp.setLinkEntityId(EntityIds.B);
		bp.setLinkBeanType(B.class);
		bp.setLinkedEntityId(EntityIds.B);
		bp.setSourceProperties(B.A_ID_PROPERTY);
		bp.setLinkDeleterService(null);
		bp.setSymmetric(true);
	}
```

Bezug zum Ticket: das FormPlugin sowie die FormLayouterFactory beziehen sich auf Entity ```B```. Wird also über die Link-Ansicht von ```A``` ein neues Objekt ```B``` angelegt, kommt die Exception.

**Comment by herrgrossmann** [comment]
Habe versucht den Fehler im kitchensink 2 example nachzustellen. 

https://github.com/jo-source/jo-client-platform-samples/tree/ISSUE_28_Reproduction/kitchensink/sample2/modules

Habe die Verlinkung zwischen Person (A) und Phone (B) exemplarisch so wie oben beschrieben angepasst.

Im SampleEntityServiceBuilder Zeile 337 - 345 werden die Beans verlinkt
https://github.com/jo-source/jo-client-platform-samples/blob/ISSUE_28_Reproduction/kitchensink/sample2/modules/app/org.jowidgets.samples.kitchensink.sample2.app.service/src/main/java/org/jowidgets/samples/kitchensink/sample2/app/service/entity/SampleEntityServiceBuilder.java

private void addPersonsOfPhonesLinkDescriptor(final IBeanEntityBluePrint entityBp) { 
338 		final IBeanEntityLinkBluePrint bp = entityBp.addLink(); 
339 		bp.setLinkEntityId(EntityIds.PHONE); 
340 		bp.setLinkBeanTypeId(Phone.class); 
341 		bp.setLinkedEntityId(EntityIds.PHONE); 
342 		bp.setSourceProperties(Phone.PERSON_ID_PROPERTY); 
343 		bp.setLinkDeleterService(null); 
344 		bp.setSymmetric(true); 
345 	} 


Das BeanForm Plugin findet sich hier:
https://github.com/jo-source/jo-client-platform-samples/blob/ISSUE_28_Reproduction/kitchensink/sample2/modules/plugins/org.jowidgets.samples.kitchensink.sample2.plugins.ui/src/main/java/org/jowidgets/samples/kitchensink/sample2/plugins/ui/form/PhoneFormPlugin.java

public final class PhoneFormPlugin extends AbstractBeanFormPlugin { 
41 
 
42 	@Override 
43 	protected void modifySetup(final IBeanFormBluePrint<?> bluePrint) { 
44 		bluePrint.setCreateModeLayouter(createLayout(false)); 
45 		bluePrint.setEditModeLayouter(createLayout(true)); 
46 	} 
47 
 
48 	public static IBeanFormLayouter createLayout(final boolean editMode) { 
49 		final IBeanFormLayoutBuilder builder = BeanFormToolkit.layoutBuilder(); 
50 		builder.addGroup(createGroup(editMode)); 
51 		return BeanFormToolkit.layouter(builder.build()); 
52 	} 
53 
 
54 	private static IBeanFormGroup createGroup(final boolean editMode) { 
55 		final IBeanFormGroupBuilder builder = BeanFormToolkit.groupBuilder(); 
56 		builder.addProperty(IPhone.PHONE_PROPERTY); 
57 
 
58 		if (editMode) { 
59 			builder.addProperty(IPhone.CREATION_DATE_PROPERTY); 
60 		} 
61 
 
62 		return builder.build(); 
63 	} 
64 } 

Wenn ich nun für eine Person ein Phone erzeuge, kommt weder das edit Formular und somit auch nicht der Fehler.

Wenn ich allerdings den folgenden Default nicht setze habe ich den Fehler auch, allerdings nicht beim Verlinken, sondern bei der Anzeige des Bearbeiten Formulars, also wenn man zum Beispiel im Tree auf ein Phone klickt. Wenn man noch gar kein Phone hat und das erste anlegt und anschließend auf den neuen Knoten im Baum klickt, dann kommt der Fehler auch. Kann es sein, dass du diesen Fehler meinst?

https://github.com/jo-source/jo-client-platform-samples/blob/ISSUE_28_Reproduction/kitchensink/sample2/modules/app/org.jowidgets.samples.kitchensink.sample2.app.ui/src/main/java/org/jowidgets/samples/kitchensink/sample2/app/ui/initializer/SampleDefaultsInitializer.java

bppf.addDefaultsInitializer(IBeanSelectionFormBluePrint.class, new IDefaultInitializer<IBeanSelectionFormBluePrint>() {
			@Override
			public void initialize(final IBeanSelectionFormBluePrint bluePrint) {
				bluePrint.setHideReadonlyAttributes(false);
			}
		});

Versuch doch mal das obige zu deinen Defaults hinzuzufügen. Tritt dann der Fehler noch auf?

Wenn ja, kann du versuchen das Phone Beispiel auf dem Branch so anzupassen, dass der Fehler auftritt?

**Comment by abentele** [comment]
zu deinem Kommentar bezügl. bluePrint.setHideReadonlyAttributes(false);:
- diese Zeilen haben weder in meiner Applikation noch im Sample eine Auswirkung in bezug auf den Fehler, d.h. der Fehler tritt auf ob man die Zeilen hinzufügt oder weglässt

Ich habe das Sample so angepasst, dass sich der Fehler jetzt reproduzieren lässt.

Definiere: steps to reproduce:
- unter "Users" ein Person-Objekt anlegen
- unter "User links" rechte Maustaste auf Unterknoten "<Phones>", dann Action "Add phones..." wählen => Fehlerdialog kommt

Meine Änderungen:
- Methode addPersonsOfPhonesLinkDescriptor: dies war die falsche Methode (zumindest in bezug auf die von mir genannten "steps to reproduce"); außerdem war die Richtung falsch implementiert => habe ich korrigiert (ist aber für o.g. "steps to reproduce" nicht relevant)
- Methode addPhonesofPersonsLinkDescriptor: folgende Zeile auskommentiert
bp.setLinkableEntityId(EntityIds.LINKABLE_PHONES_OF_PERSONS);
(dies war wohl die entscheidende Änderung)

Ich stelle die Änderung als Pull request rein (auch wenn sie fast trivial ist ...)

**Comment by herrgrossmann** [comment]
Der Commit https://github.com/jo-source/jo-client-platform/commit/88c3bf1f0bea9a5360dded1aa2acedf48036a636 hat den Fehler behoben. Der Bugfix ist ab jo-client-platform Version 0.50.0 verfügbar.

**Comment by abentele** [comment]
Test mit unserer Anwendung: ok!
