### ISSUE TITLE
 Copy Action ist aktiv obwohl keine CREATE-Permission vorhanden

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#29]
Beispiel: der User hat kein Recht CREATE_PERSON. Trotzdem ist die Copy-Action für PERSON in Tabellen und für Links aktiv.

Wird dann ein PERSON-Objekt kopiert, und dann der Speichern-Button gedrückt, kommt eine Fehlermeldung mit einem technischen Text (so ähnlich: "Create-Service nicht vorhanden").

Ich habe das Problem im Prinzip schon gelöst durch eine eigene Implementierung vn IBeanTableMenuInterceptorPlugin bzw. für Trees IBeanRelationTreePlugin und IBeanRelationTreeMenuInterceptor um jeweils den copyActionBuilder zu konfigurieren mit einem entsprechenden EnabledChecker. Ich bin aber der Meinung, dass das auch bereits generisch im Framework gemacht werden könnte. Bitte dies selber einschätzen/beurteilen. Insofern keine hohe Priorität für uns.

Meine interne Ticket-Nr:  #8045

**Comment by herrgrossmann** [comment]
Die Copy Action sollte man auch bei Readonly Rechten haben den:
1. Copy und Paste in ein Textdokument soll bei nur leserechten möglich sein
2. Man kann auch aus einem Client mit Readonly Datensätze in einen Client mit Schreibrechten Kopieren

Die Paste Action sollte jedoch nur vorhanden sein, wenn man Rechte zum Speichern hat. Im IReanRelationTree ist das bereits der Fall. In der BeanTable wurde das jetzt auch so umgesetzt. Der Bugfix ist mit Release 0.48.0 verfügbar.

**Comment by abentele** [comment]
Verifiziert: Test ok.
