### ISSUE TITLE
Edit actions sind aktiv, obwohl keine Update-Rechte vorhanden

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#30]
Es geht um folgende Actions:

BeanTableSetToAllActionBuilder.setToSelection=%1 '%2' für selektierte '%3' übernehmen
BeanTableSetToAllActionBuilder.setToAll=%1 '%2' für alle '%3' übernehmen
BeanTableSetToAllActionBuilder.notSet=-- nicht gesetzt --
BeanTableEditAllActionBuilder.editAll=Bearbeite '%1' für alle '%2'
BeanTableEditSelectionActionBuilder.editSelection=Bearbeite '%1' für selektierte '%2'

Diese Actions werden zum Teil bei uns verwendet und sind immer enabled, obwohl der User kein Update-Recht für das entsprechende Bean hat (entsprechend UpdateAuthorization annotation auf dem Hibernate Bean).

**Comment by herrgrossmann** [comment]
Bugfix ist ab Version 0.48.0 verfügbar

**Comment by abentele** [comment]
Verifiziert: Test ok.
