### ISSUE TITLE
CachedEntityService returns EntityInfo for unknown entities (Original title: NullPointerException beim Öffnen eines Panels (Ergebnis von Service-Aufrufen null bei Überlast?))

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#32]
ab und zu kommt folgende Exception beim Öffnen eines Panels:

```
java.lang.NullPointerException
	at java.util.LinkedList.addAll(Unknown Source)
	at java.util.LinkedList.addAll(Unknown Source)
	at java.util.LinkedList.<init>(Unknown Source)
	at org.jowidgets.cap.ui.impl.AbstractBeanModelBuilderImpl.getAttributes(AbstractBeanModelBuilderImpl.java:308)
	at org.jowidgets.cap.ui.impl.BeanRelationNodeModelBluePrint.getChildRenderer(BeanRelationNodeModelBluePrint.java:185)
...
```

Ursache:
- in org.jowidgets.cap.ui.impl.AbstractBeanModelBuilderImpl.AbstractBeanModelBuilderImpl(Object, Object, Class) ist ein Aufruf von entityService.getDescriptor(this.entityId), und dessen Rückgabewert ist (sporadisch) null; daraus folgt attributes == null, und daraus die o.g. NullPointerException
- in MessageBroker, Zeile 228 ist in diesem Fall msg.result == null
=> Frage: liefert der Remote service schon kein Ergebnis bzw. null, und warum?

Der Effekt konnte beobachtet werden, solange die (virtuelle) Maschine, auf der der Service lief, stark überlastet war (ESX-Überlast). Nach Behebung des Last-Problems konnte der Fehler nicht mehr beobachtet werden.

**Comment by abentele** [comment]
Update: weitere Beobachtung des Bugs, trat kurz nach Initialisierung eines Systems auf; 
internes Ticket: #10063

**Comment by herrgrossmann** [comment]
Ursache liegt vermutlich in der Änderung: 

https://github.com/jo-source/jo-client-platform/commit/92d0477b4ee68f962abc30de20283c07821dcd88

und tritt genau dann auf, wenn mehrere Entity Service Implementierungen vorhanden sind,

Der CachedEntityService gibt für unbekannte EntityIds einen NullEntityInfoEintrag zurück. Der CompositeEntityService (EntityServiveResolver) geht davon aus, dass für die EntityId ein EntityInfo vorhanden ist, und prüft nicht die weiteren EntityService Implementierungen.

**Comment by herrgrossmann** [comment]
Available in 0.58.0
