### ISSUE TITLE
Meldung "The server is not responding" beim Login

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#33]
Wenn man sich einloggt, kommt oft erstmal "The server is not responding" (Fehlermeldung angezeigt im Login-Dialog), obwohl der Server schon längst gestartet wurde und läuft, jedoch nach längerer Nichtverwendung der Applikation auf diesem Server. Nach mehrmaligem Probieren geht es dann. Weder im Server-Log noch im Client-Log findet man einen entsprechenden Log-Eintrag der die technische Ursache darstellt, was ebenfalls schlecht ist.

Vermutung: der Server braucht eine gewisse Aufweckzeit, sodass die ersten Anfragen länger dauern... (wie auch immer die technische Ursache dafür ist). Deshalb kommt es zu einem Timeout bei der Anfrage.

Falls es am Timeout liegt: dieser ist wahrscheinlich zu kurz, denn die Meldung kommt recht schnell.

Mein internes Ticket: #8039

**Comment by herrgrossmann** [comment]
Fix ist ab 0.50.0 verfügbar. Eventuell wird ein eigener Timeout in Kombination mit den Klassen RemotingBasicAuthenticationLoginInterceptor, RemotingServiceInitializer, RemotingServiceProviderFactory, SyncInvocationCallback verwendet. Falls Problem mit 0.50.0 weiter auftritt bitte prüfen, mit welchem Timeout das Remoting initialisiert wird

**Comment by abentele** [comment]
Beim Test nicht mehr aufgetreten. Ich werde es weiter beobachten.
