### ISSUE TITLE
NullPointerException in BeanProxyImpl

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#35]
in org.jowidgets.cap.ui-0.48.0:
BeanProxyImpl, Zeile 1249
executionTask ist null => NullPointerException

Da die Exception in Zeile 1264 bereits "still" gefangen wird, fällt sie nicht weiter auf. Mir ist nicht klar, ob es eine negative Auswirkung gibt. Mich stört die Exception aber beim Debuggen.

Die Exception tritt bei uns auf, wenn man einen Link hinzufügt, mit der Möglichkeit aus vorhandenen Datensätzen auszuwählen oder einen neuen Datensatz hinzuzufügen. Genauer gesagt in dem Moment wo man auf die Aktion zum Hinzufügen des Links klickt. Außerdem fliegt die Exception, wenn man im Dialog etwas eingibt, wodurch die Tabelle weiter gefiltert wird.

**Comment by herrgrossmann** [comment]
Der Bugfix ist ab Version 0.50.0 verfügbat
