### ISSUE TITLE
Logging von Exceptions im Service

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#36]
Tritt im Service eine Exception (z.B. NullPointerException) auf, wird diese i.d.R. nicht im Service log geloggt, sondern nur im Client.

Wir möchten, dass die Exception auch im Service log erscheint.

Bitte nicht nur Exceptions, sondern auch Errors bzw. Throwable loggen (ich musste heute relativ aufwändig remote debuggen, nur weil ein UnsupportedClassVersionError nicht im Service geloggt wurde)

**Comment by herrgrossmann** [comment]
Für die JPA Services kann ein logger registriert werden. Ein Beispiel findet sich im comit des KicthensinkExample2 https://github.com/jo-source/jo-client-platform-samples/commit/054c1dd1ae97b7ae956b3ec58d4c5f0e8f1844e8

Für das Messaging benötigt man einen ExceptionCallback, indem man auch loggen kann. Da das Messaging transparent für die Services ist, muss dieser Callback zusätzlich registriert werden. Dort fliegen fehler der transpoortschicht z.B. beii Connectionproblemen. Der folgende comit zeigt ein Beispiel für die Benutzung

**Comment by abentele** [comment]
Ich finde den Lösungsvorschlag nicht optimal. Gibt es einen Grund, warum die jo-client-platform nicht selber (ohne derartige Konfiguration) Fehler loggt? Ich kann mir nicht vorstellen, dass das jemand nicht wollen würde. Warum muss man also erst etwas registrieren oder konfigurieren, damit man ein Verhalten bekommt, das man einfach generell erwartet?

Für mich wäre es zwar kein sehr großer Aufwand, das bei uns einzubauen wie im Beispiel, aber immerhin muss ich es in allen Projekten bzw. relevanten branches so umsetzen. Wäre das Logging dagegen per Default drin, müsste ich gar nichts extra machen.

**Comment by herrgrossmann** [comment]
Das wurde bewusst so entschieden um Abhängigkeiten zu loggingcframworks zu vermeiden. Leider haben alle mir bekannten loggingcframworks versionsprobleme die zu Inkompatibilitäten mit anderen libraries führen. Aktuell gibt es also nur diese Möglichkeit.

Von meinem iPhone gesendet

**Comment by herrgrossmann** [comment]
Beispiele für Probleme mit SLF4J:

http://stackoverflow.com/questions/8921382/maven-slf4j-version-conflict-when-using-two-different-dependencies-that-requi

http://stackoverflow.com/questions/5477942/slf4j-version-conflict-while-building-through-the-maven

Ich bin mir bewusst, das das alles lösbare Probleme sind, aber sie sind auch unnötig. In Kombination mit log4j unter slf4j hatten wir in einem anderen Projekt erst Probleme in Kombination mit OSGi.

Ich finde es generell schlecht, wenn ein verwendetes Loggingframework verhindert, dass der Code überhaupt läuft, anstatt einfach nicht zu loggen.

Die aktuelle Lösungs in jo finde ich auch nicht optimal, den Ansatz aber schon. Ein Framework hat seine eigene Logging Fassade die es zum loggen verwendet und bietet Implementierungen für unterschiedliche Loggingframeworks. Die Fassade sollte von keinem anderen Framework verwendet werden. Ändert sich die API (das sollte sie möglichst nicht tun) ändert sich zusammen auch die Frameworkversion. Dadurch kann es keine Versionskonlikte geben. Mit diesem Vorgehen kann man das Framework mit jedem beliebigen Loggingframework verwenden und zur Not selbst einen Adapter schreiben.

Was ich aktuell bei der jo Variante nicht so gut finde ist, dass diese Fassade nicht klar definiert ist (mehrere Schnittstellen und Punkte wo man die setzen muss) und sich Logausgaben nicht nach Klassen und Loglevel trennen lassen. Hier würde ich gern nacharbeiten, ist aber eine Prioritätenfrage.

Eine direkte Abhängigkeit zu SLF4J oder einer anderen Logingsfassade habe ich in keinem Fall vor hinzuzufügen.

Um zu verhindern, dass du in unterschiedlichen Projekten jeweils einen Logger hinzufügen musst, kannst du dir ja einen FirmaXZYServiceBuilder erstellen, der alles per default so einrichtet, wie es bei euch passt. Ich sehe nicht, wieso man dann Code duplizieren muss. Zudem halte ich es für eine gute Idee, ein Framework an die firmeninternen Vorgaben anpassen zu können.

**Comment by herrgrossmann** [comment]
Ab jowidgets Version 0.58.0 (derzeit noch nicht released) gibt es in jowidgets eine logging api. Das modul org.jowidgets.logging.api liefert eine Logging Fassade, welche intern von jowidgets und der jo-client-platform verwendet wird, um zu loggen. 

Zur API gibt es aktuell die folgenden logging adapter:

- org.jowidgets.addons.logging.slf4j
- org.jowidgets.addons.logging.jul
- org.jowidgets.addons.logging.nop

Um zum Beispiel slf4j zu verwenden, kann man im verwendenden Projekt die folgende Dependency hinzufügen:

``      <dependency>
``	       <groupId>org.jowidgets</groupId>
``	       <artifactId>org.jowidgets.addons.logging.slf4j</artifactId>
``	       <version>${jowidgets.version}</version>
``	 </dependency>

Die entsprechenden slf4j Abhängigkeiten müssen dann zudem vom verwendenden Projekt hinzugefügt werden, z.B.:

``        <dependency>
``	        <groupId>org.slf4j</groupId>
``	        <artifactId>slf4j-log4j12</artifactId>
``	        <version>1.7.12</version>
``        </dependency>

Issue wird geschlossen, nachdem das Release erstellt wurde.

**Comment by herrgrossmann** [comment]
Releases jowidgets 0.58.0 und jo-client-platform 0.51.0 wurden erstellt.

**Comment by herrgrossmann** [comment]
Ab jowidgets version 0.59.0 ist die slf4j implementierung umbenannt in:

- org.jowidgets.addons.logging.slf4j161

da diese die SLF4J API Version 1.6.1 verwendet. 

Sorry für die Umstände, aber ohne Versionsangabe finde ich das verwirrend, falls in der Zukunft weitere SLF4J API Versionen benötigt werden. Da will ich lieber gleich aufräumen, bevor das noch mehr Leute verwenden:-(

In Maven sieht das dann also so aus:

`      <dependency>`
`	       <groupId>org.jowidgets</groupId>`
`	      <artifactId>org.jowidgets.addons.logging.slf4j161</artifactId>`
`	       <version>${jowidgets.version}</version>`
`	</dependency>`

Die entsprechenden slf4j Abhängigkeiten müssen dann zudem vom verwendenden Projekt hinzugefügt werden, falls nicht bereits vorhanden, Mit dem folgenden SLF4J Adapter hab ich das getestet:

`        <dependency>`
`	        <groupId>org.slf4j</groupId>`
`	        <artifactId>slf4j-log4j12</artifactId>`
`	        <version>1.7.12</version>`
`         </dependency>`
