### ISSUE TITLE
userQuestion in dekoriertem Service führt zu client freeze

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#40]
Folgender Fall:
- dekorierter CreatorService (implements ICreatorService)
- dieser ruft in der create-Methode folgenden Code auf
```java
final UserQuestionResult questionResult = executionCallback.userQuestion(questionMessage);
```
- es wird ein entsprechender Confirmation-Dialog im Client angezeigt; dieser lässt sich aber nicht bedienen, d.h. die Buttons können nicht angeklickt werden und auch der Close-Button des Fensters bewirkt nichts

Der Fehler kam rein mit dem Versionssprung 0.49.0 auf 0.50.0.
Genauer:
- mit commit 88c3bf1f0bea9a5360dded1aa2acedf48036a636 funktioniert es noch korrekt
- mit dem darauf folgenden commit 04d381a8620781fe94c9a9c9b9769f728404366d funktioniert es nicht mehr

Bei der Änderung wurden die Methoden in der Klasse ExecutionTask synchronisiert, um Ticket #21 zu lösen. Im Thread dump sieht man, dass mehrere Threads Methoden von ExecutionTask aufrufen, und manche blockiert sind wegen dem synchronized.

**Comment by herrgrossmann** [comment]
Fixed in version 0.55.0
