### ISSUE TITLE
Selection lost in BeanTable when sorting twice in quick succession

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-client-platform#41]
Changing between columns for sorting leads to loss of current selection. 

reproduction:
1. select a row
2. click between columns 
-> 4 fast clicks between 2 columns will usually be sufficient to lose selection

**Comment by herrgrossmann** [comment]
Cherry picked pull request

**Comment by herrgrossmann** [comment]
Availaible in  0.56.0
