### ISSUE TITLE
JpaServiceDecorator PersistenceUnitName 

### ISSUE THREAD

**Issue by xanatos1992** [jo-source/jo-client-platform#43]
The org.jowidgets.cap.service.jpa.impl.JpaServicesDecoratorProviderImpl does not check the persistenc unitname from the entitymanager when this is not null. 

This creates a possible error when there is a entitymanager but with the wrong persistence unitname.

**Comment by herrgrossmann** [comment]
Merged pull request

**Comment by herrgrossmann** [comment]
Available in 0.56.0
