### ISSUE TITLE
Class cast Exception when creating linked bean with IBeanValidator

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-client-platform#46]
Given 
  two bean types with a 1:n link (does not occur with n:m links) 
  and an IBeanValidator on one of them,
when 
  you create a bean via the TreeBrowser from a bean of the other type (direction does not matter)
then 
  a ClassCast exception occurs: java.lang.ClassCastException: [Some custom class implementing IBeanValidator] cannot be cast to org.jowidgets.cap.ui.api.bean.IBeanPropertyValidator at org.jowidgets.cap.ui.impl.BeanProxyImpl.getDependendProperties(BeanProxyImpl.java:679)

The culprit seems to be line 172 of org.jowidgets.cap.ui.impl.LinkCreatorActionBuilderImpl
where a type incompatibility is maske d by a cast.

The bug has been reproduced in the kitchen sink sample 2 by adding an IBEanValidator to ICategory.
See branch "Reproduce_issue_46" in jo-client-platform-samples.
Steps to reproduce:
 1. Open the kitchen sink 2 workbench (starter does not matter, I used the Swing standalone one)
 2. Create a Category
 3. go to the "Category links" tree brwoser
 4. Create a sub or super category via context menue
--> ClassCastException

**Comment by herrgrossmann** [comment]
Was fixed with issue #48

**Comment by herrgrossmann** [comment]
Will be available in 0.56.0
