### ISSUE TITLE
MenuInterceptor for BeanReleationTree will not be invoked for root node

### ISSUE THREAD

**Issue by herrgrossmann** [jo-source/jo-client-platform#47]
The method:

IMenuModel nodeMenu(IBeanRelationNodeModel<Object, Object> relationNode, IMenuModel menuModel);

of the interface:

org.jowidgets.cap.ui.api.tree.IBeanRelationTreeMenuInterceptor

will not be invoked for root nodes of bean relation trees

**Comment by herrgrossmann** [comment]
Fixed with release 0.56.0 comming soon

**Comment by abentele** [comment]
Ticket im Redmine

--
Andreas Bentele
Weinbirnenstraße 35
88048 Friedrichshafen

Telefon: 07541 289240
Handy: 0160 8595363
E-Mail: andreas.bentele@me.com
