### ISSUE TITLE
Validation Warning persists after undo in BeanTable

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-client-platform#50]
If 
- there is a validation error in a transient, i.e. new and unsaved, bean.
- a TableCellEditor is open for one of the bean's attributes 
- undo is invoked

then 
- the validation error remains. No further revert or reload can remove it. It prevents saving.

Debugging showed that 
- the validation error is removed correctly at first when the bean is removed
- but is reintroduced when the TableCellEditor is disposed.

**Comment by herrgrossmann** [comment]
Fixed in 0.58.0
